name: Build and Push Docker Image

on:
  # This workflow runs automatically whenever you push to the 'main' branch
  push:
    branches: [ "main" ]
  # This allows you to run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use a standard Linux runner from GitHub

    steps:
      # 1. Get a copy of your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Log in to Docker Hub using the secrets you created
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build the Docker image and push it to your Docker Hub account
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: caracasradu11973/rvc-api:latest # IMPORTANT: Change this line!
